Project/project/pages/urls.py
from django.urls import path
from .import views
urlpatterns = [


    path('aboutus', views.AboutUs.as_view(), name='about'),
    path('', views.HomeView.as_view(), name='index'),
    path('settings/', views.Setting.as_view(), name='setting')


]

Project/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('house/', include('properties.urls')),
    path('', include('pages.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/project/properties/urls.py
from django.urls import path


from .import views
urlpatterns = [
    path('details/<int:pk>', views.HouseDetails.as_view()),
    path('houses/', views.HouseView.as_view()),
    path('details/', views.Details.as_view(), name='details'),
    path('filter/', views.Filter.as_view(), name='filter'),
    path('filter2/', views.Filter2.as_view(), name='filter2'),
    path('filter3/', views.Filter3.as_view(), name='filter3'),
    path('sell/', views.Sell12.as_view(), name='sell'),
    # path('sell3/', views.Sell3.as_view(), name='sell3'),
    path('sell4/', views.Sell4.as_view(), name='sell4'),
    path('thankyou/', views.ThankYou.as_view(), name='thankyou'),
    path('result/', views.Prediction, name='Prediction'),
    path('index/', views.Result.as_view(), name='index'),
    path('allhouses/', views.PropView, name='allhouses'),
    path('<int:id>/', views.detail_view, name='detail'),
    path('sell3/', views.sell3, name='sell3'),
    # path('success', views.success, name='success'),

]

Project/project/properties/models.py
from decimal import Decimal
from multiprocessing.sharedctypes import Value
from django.db import models
from datetime import datetime  # create intial datetime value
from django.contrib.auth.models import User
from xml.dom.minidom import CharacterData
from django.forms import CharField
from matplotlib.style import context
from users.models import profile
from datetime import datetime
from django.shortcuts import render


class property_type(models.Model):
    type = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.type


class Property(models.Model):

    bedrooms = models.IntegerField(
        null=True)
    bathrooms = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, blank=0)
    SQFT_Living = models.IntegerField(
        null=True)
    SQFT_lot = models.IntegerField(
        null=True)
    floors = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, blank=0)
    waterfront = models.IntegerField(
        null=True)
    view = models.IntegerField(
        null=True)
    condition = models.IntegerField(
        null=True)
    grade = models.IntegerField(
        null=True)
    SQFT_above = models.IntegerField(
        null=True)
    SQFT_basement = models.IntegerField(
        null=True)
    yr_built = models.IntegerField(
        null=True)
    yr_renovated = models.IntegerField(
        null=True)
    zip_code = models.IntegerField(
        null=True)
    lat = models.DecimalField(
        max_digits=7, decimal_places=4, null=True)

    long = models.DecimalField(
        max_digits=7, decimal_places=3, null=True, blank=0)

    SQFT_living15 = models.IntegerField(
        null=True)

    SQFT_lot15 = models.IntegerField(
        null=True)

    price = models.DecimalField(
        max_digits=10, decimal_places=3, null=True)

    created = models.DateTimeField(default=datetime.now)
    # user upload prop relation
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    city = models.CharField(max_length=50, null=True)
    type = models.ForeignKey(
        property_type, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=150)  # 0
    image = models.FileField(blank=True, null=True)
    active = models.BooleanField(default=True)
    description = models.TextField(null=True)

    def __str__(self):
        return self.title  # return the house name in the admin panel


class PropImage(models.Model):
    property = models.ForeignKey(
        Property, default=None, on_delete=models.CASCADE)
    images = models.FileField(upload_to='images/')


class UploadedProb(models.Model):  # model for user to upload properites
    type = models.ForeignKey(
        property_type, on_delete=models.CASCADE, null=True)
    prop_kind = models.CharField(max_length=100, null=True)
    images = models.ImageField(upload_to='images/', null=True)
    videos = models.FileField(upload_to='images/', null=True)
    city = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=300, null=True)
    location = models.URLField(null=True)
    profile = models.OneToOneField(

        profile, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.prop_kind

Project/project/properties/forms.py
# forms.py
from django import forms
from .models import *

from django.contrib.auth import password_validation

from django import forms
import django
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.db import models
from django.db.models import fields
from django.forms import widgets
from django.forms.fields import CharField
from django.utils.translation import gettext, gettext_lazy as _
# TYPE_CHOICES = (
#     ('1', 'rent'),
#     ('2', 'sell')
# )


class UploadForm(forms.ModelForm):

    city = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Coupon code',
        'aria-label': "Recipient's username",
        'aria-describedby': "basic-addon2",
    }))
    prop_kind = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Coupon code',
        'aria-label': "Recipient's username",
        'aria-describedby': "basic-addon2",
    }))

    # type = forms.ChoiceField(widget=forms.RadioSelect, choices=TYPE_CHOICES)
    videos = forms.CharField(widget=forms.FileInput(attrs={
        'class': 'form-control',
        'placeholder': 'Coupon code',
        'aria-label': "Recipient's username",
        'aria-describedby': "basic-addon2",
    }))
    images = forms.CharField(widget=forms.FileInput(attrs={
        'class': 'form-control',
        'placeholder': 'Coupon code',
        'aria-label': "Recipient's username",
        'aria-describedby': "basic-addon2",
    }))

    class Meta:
        model = UploadedProb
        fields = ['location', 'city', 'prop_kind', 'type', 'images', 'videos']


class Signupform (forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Project/project/properties/views.py
from .models import Property
from .models import PropImage
from .models import UploadedProb
from .filters import PropertyFilter

from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import *

from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpRequest

from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib import messages


from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, Paginator

import joblib
import xgboost as xgb
# def property(request):
#     the_Property = Property.objects.all()1

#     return render(request, 'pages/index.html', {'house': the_Property})

# product.objects.get(name=habiba)
# def detail(request):
#     Notes = Property.objects.all()
#     return render(request, 'pages/details_page.html', {'note': Notes})


class Details(TemplateView):
    template_name = 'details_page.html'


class HouseView(ListView):

    template_name = 'house.html'
    model = Property
    context_object_name = "houses"


class HouseDetails(DetailView):
    model = Property
    context_object_name = "house"
    template_name = 'details_page.html'


class Sell12(TemplateView):
    template_name = 'sell1,2.html'


# class Sell3(TemplateView):
#     template_name = 'sell 3.html'


class Sell4(TemplateView):
    template_name = 'sell-4.html'


class Filter(TemplateView):
    template_name = 'onboaded i.html'


class Filter2(TemplateView):
    template_name = 'onboaded ii.html'


class Filter3(TemplateView):
    template_name = 'onboaded iii.html'


class ThankYou(TemplateView):
    template_name = 'thank_you.html'


class Result(TemplateView):
    template_name = 'result.html'


class index(TemplateView):
    template_name = 'pages/index.html'


# def upload(request):
#     if request.method == 'POST':
#         images = ['']

#         new = UploadedProb.objects.create_new(images=images)

#     else:
#         return(request, 'pages/index.html')


def PropView(request):  # AllHousesView

    properties = Property.objects.all()
    myFilter = PropertyFilter(request.GET, queryset=properties)
    properties = myFilter.qs
    properties_paginator = Paginator(properties, 5)
    page_num = request.GET.get('page')

    page = properties_paginator.get_page(page_num)
    context = {
        'page': page,
        'count': properties_paginator.count,
        'myFilter': myFilter,

    }
    return render(request, 'all_properties.html', context)


def detail_view(request, id):  # detailhouseview
    property = get_object_or_404(Property, id=id)
    photos = PropImage.objects.filter(property=property)
    return render(request, 'details_page.html', {
        'property': property,
        'photos': photos
    })
    # def house(request):
    #     return render(request, 'pages/index.html', {'x': Property.objects.filter(price=)})


# def showthis(request):
#     Property.objects.all().delete
#     # deletes all objects from Car database table

#     context = {}
#     return render(request, 'pages/index.html', context)
# def uploadProperty(request):

# this function take the inputs  from the form in inboadedIII and deploy the ML model
def Prediction(request):
    print("hello0")

    # booster = xgboost.Booster()
    # booster.load_model('model_file_name.json')
    model2 = xgb.XGBRegressor()
    model2.load_model("final_model.bin")
    # cls = joblib.load('model.json')
    print("hello1")
    print(request.GET)
    lis = []
    # list = [2, 1, 1220, 6300, 1.0, 0, 3, 7, 760,
    #         1942, 47.5299, -122.387, 1850, 4886]
    lis.append(int(request.GET['bedrooms']))
    print(request.GET['bedrooms'])
    lis.append(float(request.GET['bathrooms']))
    print(request.GET['bathrooms'])

    lis.append(int(request.GET['SQFT_Living']))
    print(request.GET['SQFT_Living'])
    lis.append(int(request.GET['SQFT_lot']))
    print(request.GET['SQFT_lot'])
    lis.append(float(request.GET['floors']))
    print(request.GET['floors'])
    lis.append(int(request.GET['waterfront']))
    print(request.GET['waterfront'])
    lis.append(int(request.GET['condition']))
    print(request.GET['condition'])
    lis.append(int(request.GET['grade']))
    print(request.GET['grade'])
    lis.append(int(request.GET['SQFT_above']))
    print(request.GET['SQFT_above'])
    lis.append(int(request.GET['yr_built']))
    print(request.GET['yr_built'])
    lis.append(float(request.GET['lat']))
    print(request.GET['lat'])
    lis.append(float(request.GET['long']))
    print(request.GET['long'])

    lis.append(int(request.GET['SQFT_living15']))
    print(request.GET['SQFT_living15'])
    lis.append(int(request.GET['SQFT_lot15']))
    print(request.GET['SQFT_lot15'])

    print("hello2")

    ans = model2.predict([lis])
    return render(request, "result.html", {'ans': ans})


def sell3(request):
    # print("hello1")
    # if request.method == "POST":
    #     print("hello0")
    #     type = request.POST['type']
    #     location = request.POST['location']
    #     # city = request.POST['city']
    #     prop_type = request.POST['prop_type']
    #     images = request.FILES['images']
    #     videos = request.FILES['videos']

    #     myprop = UploadedProb.objects.create_upload(type,
    #                                                 location,  prop_type)
    #     myprop.images = images
    #     myprop.videos = videos
    #     print("hello2")

    #     # myuser.is_active = False
    #     myprop.is_active = False
    #     myprop.save()
    #     print("hello3")
    # return render(request, "sell 3.html")

    if request.method == 'POST':

        form = UploadForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            print("sav")
            return redirect('sell4')
    else:
        form = UploadForm()

    return render(request, 'sell 3.html', {'form': form})

Project/project/properties/templates/all_properties.html
{%extends 'parts/base.html'%} {%load static %}{%block content%}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DreamHouse</title>
    <link rel="stylesheet" href="{%static 'css/main.css'%}" />
    <link
      href="https://fonts.googleapis.com/css?family=Poppins"
      rel="stylesheet"
    />

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;700&#038;display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
    />
  </head>
  {%endblock content%} {%block content2%}

  <!-- End Header -->
  <!-- Start Filters -->
  <div class="Property_filters">
    <form class="property_filters_form">
      {{myFilter.form}}
      
      
      <div class="selector">
        <div id="selectField">
         {{count}} 
        </div>
        
      </div>
     
      <input class="submitBtn" type="submit" value="Apply" />
    </form>
  </div>
  <!-- End Filters-->
  <!-- Start All houses -->

  <div class="all-houses-section-slide">
    
    <div class="house-section-slide">
      <!-- Start Portfolio -->
      <div class="portfolio" id="portfolio">
        <div class="PortContainer">
          
          
          
          <div class="portfolio-content">
            {%for x in page.object_list %}
            <a href="{%url 'detail' x.id%}">
              <div class="PortCard">
                {% comment %} {% if x.image %} {% endcomment %}
                <img  class="cardImg" src="{{x.image.url}}" alt="">
                  {% comment %} {% endif %} {% endcomment %}
                
                <div class="info">
                  <h3 class="cardH">{{x.title}}</h3>
                  <div class="cardP">>
                  <p class="cardP">Number of floors {{x.floors}} </p>
                  </div>
                  {% comment %} <p class="cardP"> {{x.SQFT_Living}}5441 NE NEast River Rd, Chicago, IL 60656</p> {% endcomment %}
                  <p class="cardP">
                    Area: {{x.SQFT_Living}}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    Rooms: {{x.bedrooms}}
                  </p>
                </div>
              </div>
            </a>
            {%endfor %}
          </div>
          
        </div>
      </div>

      <!-- End Portfolio -->
    </div>
  </div>
  
  
    <div class="dot-container">
    {%if page.has_previous%}
      <a href="{%url 'allhouses'%}?page={{page.previous_page_number}}"
        >previous  ></a
      >
      {%endif%}  
       {%if page.has_next %}
      <a href="{%url 'allhouses'%}?page={{page.next_page_number}}"> next ></a>
      {%endif%}
    </div>
  
  </div>
  <!--End All houses-->
  <!-- Start Footer -->

  <script>
    var selectField = document.getElementById("selectField");
    var selectText = document.getElementById("selectText");
    var options = document.getElementsByClassName("options");
    var list = document.getElementById("list");
    var arrowIcon = document.getElementById("arrowIcon");

    selectField.onclick = function () {
      list.classList.toggle("hide");
      arrowIcon.classList.toggle("rotate");
    };
    for (option of options) {
      option.onclick = function () {
        selectText.innerHTML = this.textContent;
        list.classList.toggle("hide");
        arrowIcon.classList.toggle("rotate");
      };
    }

    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
      showSlides((slideIndex += n));
    }

    function currentSlide(n) {
      showSlides((slideIndex = n));
    }

    function showSlides(n) {
      var i;
      var slides = document.getElementsByClassName("house-section-slide");
      var dots = document.getElementsByClassName("pageDot");
      if (n > slides.length) {
        slideIndex = 1;
      }
      if (n < 1) {
        slideIndex = slides.length;
      }
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
      }
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex - 1].style.display = "block";
      dots[slideIndex - 1].className += " active";
    }
  </script>
</html>
{%endblock content2%}

Project/project/properties/templates/house.html
{%extends 'parts/base.html'%} {%load static %}{%block content%}
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>DreamHouse</title>
  <link rel="stylesheet" href="{%static 'css/main.css'%}" />
  <link rel="stylesheet" href="{%static 'css/details_Result.css'%}" />
  <link
    href="https://fonts.googleapis.com/css?family=Poppins"
    rel="stylesheet"
  />

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;700&#038;display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
  />
</head>
{% comment %}
<body>
  {%for house in houses%}<br />
  {{house.bedrooms}} <br />{{house.views}} <br />
  {{house.address}} <br />{{house.image}} <br />
  {{house.city}}{% endfor %}
</body>
{% endcomment %} {%endblock content%} {%block content2%}
<body>
  {%for house in houses%}<br />
  {{house.bedrooms}} <br />{{house.views}} <br />
  {{house.address}} <br />{{house.image}} <br />
  {{house.city}}{% endfor %}
</body>

{%endblock content2%}

Project/project/properties/templates/sell 3.html
{%extends 'parts/base.html'%}{%load static %} {%block content%} {%load static%}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DreamHouse</title>
    <link rel="stylesheet" href="{%static 'css/main.css'%}" />
    <link rel="stylesheet" href="{%static 'css/onboaded.css'%}" />
    <link rel="stylesheet" href="{%static 'css/sell1,2.css'%}" />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

    <link
      href="https://fonts.googleapis.com/css?family=Poppins"
      rel="stylesheet"
    />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{%static 'css/all.min.css'%}" />
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;700&#038;display=swap"
      rel="stylesheet"
    />
    {% comment %}
    <script type="text/javascript" src="{%static 'JS/popup.js'%}"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
      integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
    />
    {% endcomment %}
  </head>
  {%endblock content%} {%block content2%}

  <!-- Start Header -->

  <!-- End Header -->
  <!-- Start Sell Landing -->
  <div class="sell_3_landing_phrase">
    <p>Let us find your customer!</p>
  </div>
  <!-- End Sell Landing -->
  <!-- Start Form -->
  <div
    style="width: 500px"
    class="d-flex justify-content-center align-items-center"
  >
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit"><a href="{%url 'sell4'%}"></a>Upload</button>
    </form>
  </div>

  <!--End Form -->
  {% comment %}
  <form method="POST">
    {% csrf_token %}
    <div class="Form">
      <div class="property_felters">
        <div class="operation_Type" id="sell3_operation_type">
          <div class="Select_boxes">
            <p>
              <label for="id_type">Type:</label>

              <select name="type" required="" id="id_type">
                <option value="" selected="">---------</option>

                <option value="1">rent</option>

                <option value="2">sell</option>
              </select>
            </p>
          </div>
        </div>
        <div class="Select_boxes">
          <div class="sell_3_input">
            <p>Location</p>
            <input
              type="url"
              list="sell-city-input"
              placeholder="Select"
              name="location"
            />
          </div>

          <div class="sell_3_input">
            <p>property Kind</p>
            <input
              type="list"
              list="sell-property-input"
              placeholder="Select"
              name="prop_type"
            />
            <datalist id="sell-property-input">
              <option value="Villa"></option>
              <option value="Duplex"></option>
              <option value="Apartment"></option>
            </datalist>
          </div>
        </div>
      </div>
      <div class="property_pic">
        <p class="property_headding">Photos for your property</p>
        <div class="pic_vid_container">
          <img src="../assets/img-stack 1.png" />
          <p class="input-img-vid-details">
            Please drag and drop Add 5:10 images
          </p>
          <label
            ><input type="file" name="images" required />
            Upload your images
          </label>
        </div>
      </div>
      <div class="property_vid">
        <p class="property_headding">Videos for your property</p>
        <div class="pic_vid_container">
          <img src="../assets/video-gallery-2 1.png" />
          <p class="input-img-vid-details">
            Please add a video for your entire property
          </p>
          <label>
            <input type="file" name="videos" required />
            Upload your Videos
          </label>
        </div>
      </div>
      <div class="owner_details">
        <div class="details_coloumn">
          <p>
            We will call you in 2 days so we can fill out the rest of
            information and recommend it to our user
          </p>
          <a href="{%url 'index'%}"
            ><button type="submit"><span>Send</span></button></a
          >
        </div>
      </div>
    </div>
  </form>
  {% endcomment %}
</html>
{%endblock content2%}

Project/project/properties/templates/sell-4.html
{%load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DreamHouse</title>
    <!-- main css file -->
    <link rel="stylesheet" href="{%static 'css/find.css'%}" />

    <!-- render all elemnts normally -->
    <link rel="stylesheet" href="{%static 'css/thank_you.css'%}" />
    <link rel="stylesheet" href="{%static 'css/all.min.css'%}" />
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,400;0,700;0,800;1,200;1,500&display=swap"
      rel="stylesheet"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&family=Work+Sans:ital,wght@0,400;0,700;0,800;1,200;1,500&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="header" id="header">
      <a href="{%url 'index'%}" class="logo"
        ><img src="{%static 'assets/logo.png'%}" alt="Dream House"
      /></a>
    </div>
    <div class="thank">
      <a href="#" class="logo"
        ><img
          src="{%static 'assets/neo-sakura-success 1.png'%}"
          alt="Dream House"
      /></a>
      <p class="firstp">Thank you!</p>
      <br />
      <p class="secondp">
        We will call you in the next hours to finish all steps
      </p>
      <button><a href="{%url 'index'%}">Home</a></button>
    </div>
  </body>
</html>

Project/project/properties/templates/thank_you.html
{%extends 'parts/base.html'%}{%load static %} {%block content%}
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>DreamHouse</title>
  <link rel="stylesheet" href="{%static 'css/main.css'%}" />
  <link rel="stylesheet" href="{%static 'css/details_Result.css'%}" />
  <link
    href="https://fonts.googleapis.com/css?family=Poppins"
    rel="stylesheet"
  />

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;700&#038;display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
  />
</head>

{% endblock content%} {%block content2%}
<body>
  <div class="thank">
    <a class="logo"
      ><img src="../assets/neo-sakura-success 1.png" alt="Dream House"
    /></a>
    <p class="firstp">Thank you!</p>
    <br />
    <p class="secondp">
      We will call you in the next hours to describe our system
    </p>
    <a class="a" href="../index.html"
      ><button><span>Home</span></button></a
    >
  </div>
</body>
{%endblock content2%}